// Generated by scripts/build-image-catalog.mjs: every website image staff can replace in Settings → Website images.
// Re-run the script after adding or removing images in the code.

export interface SiteImage { path: string; label: string; group: string; usedOn: string[]; maxWidth: number }

export const SITE_IMAGES: SiteImage[] = [
    {
        "path": "/site/about/2.jpg",
        "label": "2.jpg",
        "group": "About & company",
        "usedOn": [
            "About page"
        ],
        "maxWidth": 1400
    },
    {
        "path": "/site/about/3.jpg",
        "label": "3.jpg",
        "group": "About & company",
        "usedOn": [
            "About page"
        ],
        "maxWidth": 1400
    },
    {
        "path": "/site/about/9.jpg",
        "label": "9.jpg",
        "group": "About & company",
        "usedOn": [
            "About page"
        ],
        "maxWidth": 1400
    },
    {
        "path": "/site/img-single/1.jpg",
        "label": "1.jpg",
        "group": "About & company",
        "usedOn": [
            "About page"
        ],
        "maxWidth": 1400
    },
    {
        "path": "/site/img-single/2.jpg",
        "label": "2.jpg",
        "group": "About & company",
        "usedOn": [
            "About page",
            "Portal page"
        ],
        "maxWidth": 1400
    },
    {
        "path": "/site/img-single/ch.jpg",
        "label": "ch.jpg",
        "group": "About & company",
        "usedOn": [
            "Company history page"
        ],
        "maxWidth": 1400
    },
    {
        "path": "/site/img-single/clients2.jpg",
        "label": "clients2.jpg",
        "group": "About & company",
        "usedOn": [
            "Testimonials page"
        ],
        "maxWidth": 1400
    },
    {
        "path": "/site/banner.jpg",
        "label": "banner.jpg",
        "group": "Banners & slider",
        "usedOn": [
            "Home page"
        ],
        "maxWidth": 1920
    },
    {
        "path": "/site/parallax/bg-parallax2.jpg",
        "label": "bg-parallax2.jpg",
        "group": "Banners & slider",
        "usedOn": [
            "About page",
            "Contact page",
            "Gallery page",
            "Quote page",
            "Page banners"
        ],
        "maxWidth": 1920
    },
    {
        "path": "/site/parallax/bg-parallax3.jpg",
        "label": "bg-parallax3.jpg",
        "group": "Banners & slider",
        "usedOn": [
            "Company history page",
            "Partners page",
            "Portal page",
            "Services page",
            "Testimonials page",
            "Track page"
        ],
        "maxWidth": 1920
    },
    {
        "path": "/site/parallax/bg-parallax4.jpg",
        "label": "bg-parallax4.jpg",
        "group": "Banners & slider",
        "usedOn": [
            "Home page",
            "Portal page"
        ],
        "maxWidth": 1920
    },
    {
        "path": "/site/slides/2.jpg",
        "label": "2.jpg",
        "group": "Banners & slider",
        "usedOn": [
            "Other",
            "Home slider"
        ],
        "maxWidth": 1920
    },
    {
        "path": "/site/slides/7.jpg",
        "label": "7.jpg",
        "group": "Banners & slider",
        "usedOn": [
            "Customer portal",
            "Home slider"
        ],
        "maxWidth": 1920
    },
    {
        "path": "/site/slides/8.jpg",
        "label": "8.jpg",
        "group": "Banners & slider",
        "usedOn": [
            "Home slider"
        ],
        "maxWidth": 1920
    },
    {
        "path": "/site/client/1.png",
        "label": "Logistics",
        "group": "Client & partner logos",
        "usedOn": [
            "Partners page"
        ],
        "maxWidth": 480
    },
    {
        "path": "/site/client/2.png",
        "label": "Royal Resort",
        "group": "Client & partner logos",
        "usedOn": [
            "Partners page"
        ],
        "maxWidth": 480
    },
    {
        "path": "/site/client/3.png",
        "label": "Hexagon",
        "group": "Client & partner logos",
        "usedOn": [
            "Partners page"
        ],
        "maxWidth": 480
    },
    {
        "path": "/site/client/4.png",
        "label": "Plusinfinit",
        "group": "Client & partner logos",
        "usedOn": [
            "Partners page"
        ],
        "maxWidth": 480
    },
    {
        "path": "/site/client/5.png",
        "label": "Overseas Transport",
        "group": "Client & partner logos",
        "usedOn": [
            "Partners page"
        ],
        "maxWidth": 480
    },
    {
        "path": "/site/client/6.png",
        "label": "Construction Solutions",
        "group": "Client & partner logos",
        "usedOn": [
            "Partners page"
        ],
        "maxWidth": 480
    },
    {
        "path": "/site/client/7.png",
        "label": "Mediterranean Shipping Company",
        "group": "Client & partner logos",
        "usedOn": [
            "Partners page"
        ],
        "maxWidth": 480
    },
    {
        "path": "/site/client/8.png",
        "label": "Maersk",
        "group": "Client & partner logos",
        "usedOn": [
            "Partners page"
        ],
        "maxWidth": 480
    },
    {
        "path": "/site/client/c1.png",
        "label": "ACF International",
        "group": "Client & partner logos",
        "usedOn": [
            "Client logos"
        ],
        "maxWidth": 480
    },
    {
        "path": "/site/client/c11.png",
        "label": "International Development Law Organization",
        "group": "Client & partner logos",
        "usedOn": [
            "Client logos"
        ],
        "maxWidth": 480
    },
    {
        "path": "/site/client/c14.png",
        "label": "Medair",
        "group": "Client & partner logos",
        "usedOn": [
            "Client logos"
        ],
        "maxWidth": 480
    },
    {
        "path": "/site/client/c18.png",
        "label": "International Medical Corps",
        "group": "Client & partner logos",
        "usedOn": [
            "Client logos"
        ],
        "maxWidth": 480
    },
    {
        "path": "/site/client/c19.png",
        "label": "World Vision International",
        "group": "Client & partner logos",
        "usedOn": [
            "Client logos"
        ],
        "maxWidth": 480
    },
    {
        "path": "/site/client/c2.png",
        "label": "CISP",
        "group": "Client & partner logos",
        "usedOn": [
            "Client logos"
        ],
        "maxWidth": 480
    },
    {
        "path": "/site/client/c20.png",
        "label": "US Embassy",
        "group": "Client & partner logos",
        "usedOn": [
            "Client logos"
        ],
        "maxWidth": 480
    },
    {
        "path": "/site/client/c3.png",
        "label": "CESVI",
        "group": "Client & partner logos",
        "usedOn": [
            "Client logos"
        ],
        "maxWidth": 480
    },
    {
        "path": "/site/client/c4.png",
        "label": "International Rescue Committee",
        "group": "Client & partner logos",
        "usedOn": [
            "Client logos"
        ],
        "maxWidth": 480
    },
    {
        "path": "/site/client/c5.png",
        "label": "International Organization for Migration",
        "group": "Client & partner logos",
        "usedOn": [
            "Client logos"
        ],
        "maxWidth": 480
    },
    {
        "path": "/site/client/c8.png",
        "label": "Norwegian Red Cross",
        "group": "Client & partner logos",
        "usedOn": [
            "Client logos"
        ],
        "maxWidth": 480
    },
    {
        "path": "/site/client/c9.png",
        "label": "Danish Red Cross",
        "group": "Client & partner logos",
        "usedOn": [
            "Client logos"
        ],
        "maxWidth": 480
    },
    {
        "path": "/site/portfolio/air.jpg",
        "label": "Air delivery",
        "group": "Gallery",
        "usedOn": [
            "Gallery"
        ],
        "maxWidth": 1400
    },
    {
        "path": "/site/portfolio/cargo.jpg",
        "label": "Cargo photos 2016",
        "group": "Gallery",
        "usedOn": [
            "Gallery"
        ],
        "maxWidth": 1400
    },
    {
        "path": "/site/portfolio/cargo2.jpg",
        "label": "Cargo photos",
        "group": "Gallery",
        "usedOn": [
            "Gallery"
        ],
        "maxWidth": 1400
    },
    {
        "path": "/site/portfolio/logistics.jpg",
        "label": "Logistics photos 2016",
        "group": "Gallery",
        "usedOn": [
            "Gallery"
        ],
        "maxWidth": 1400
    },
    {
        "path": "/site/portfolio/logistics2.jpg",
        "label": "Logistics photos",
        "group": "Gallery",
        "usedOn": [
            "Gallery"
        ],
        "maxWidth": 1400
    },
    {
        "path": "/site/portfolio/sea.jpg",
        "label": "Sea delivery",
        "group": "Gallery",
        "usedOn": [
            "Gallery"
        ],
        "maxWidth": 1400
    },
    {
        "path": "/site/portfolio/transport.png",
        "label": "Transport photos",
        "group": "Gallery",
        "usedOn": [
            "Gallery"
        ],
        "maxWidth": 1400
    },
    {
        "path": "/site/portfolio/warehouse.jpg",
        "label": "Warehouse",
        "group": "Gallery",
        "usedOn": [
            "Gallery"
        ],
        "maxWidth": 1400
    },
    {
        "path": "/site/portfolio/warehouse2.jpeg",
        "label": "Warehouse",
        "group": "Gallery",
        "usedOn": [
            "Gallery"
        ],
        "maxWidth": 1400
    },
    {
        "path": "/site/blog/b10.jpg",
        "label": "b10.jpg",
        "group": "Home page",
        "usedOn": [
            "Home page"
        ],
        "maxWidth": 1400
    },
    {
        "path": "/site/blog/b7.jpg",
        "label": "b7.jpg",
        "group": "Home page",
        "usedOn": [
            "Home page"
        ],
        "maxWidth": 1400
    },
    {
        "path": "/site/blog/b8.jpg",
        "label": "b8.jpg",
        "group": "Home page",
        "usedOn": [
            "Home page"
        ],
        "maxWidth": 1400
    },
    {
        "path": "/site/imagebox/3.jpg",
        "label": "3.jpg",
        "group": "Home page",
        "usedOn": [
            "Home page"
        ],
        "maxWidth": 1400
    },
    {
        "path": "/site/imagebox/4.jpg",
        "label": "4.jpg",
        "group": "Home page",
        "usedOn": [
            "Home page"
        ],
        "maxWidth": 1400
    },
    {
        "path": "/site/imagebox/5.jpg",
        "label": "5.jpg",
        "group": "Home page",
        "usedOn": [
            "Home page"
        ],
        "maxWidth": 1400
    },
    {
        "path": "/site/404.png",
        "label": "404.png",
        "group": "Other",
        "usedOn": [
            "Other"
        ],
        "maxWidth": 1920
    },
    {
        "path": "/site/user.jpg",
        "label": "user.jpg",
        "group": "Other",
        "usedOn": [
            "Other"
        ],
        "maxWidth": 400
    },
    {
        "path": "/site/promo.jpg",
        "label": "promo.jpg",
        "group": "Promo popup",
        "usedOn": [
            "Promo popup"
        ],
        "maxWidth": 1400
    },
    {
        "path": "/site/services/1.jpg",
        "label": "1.jpg",
        "group": "Services",
        "usedOn": [
            "Service pages"
        ],
        "maxWidth": 1400
    },
    {
        "path": "/site/services/2.jpg",
        "label": "2.jpg",
        "group": "Services",
        "usedOn": [
            "Service pages"
        ],
        "maxWidth": 1400
    },
    {
        "path": "/site/services/3.jpg",
        "label": "3.jpg",
        "group": "Services",
        "usedOn": [
            "Service pages"
        ],
        "maxWidth": 1400
    },
    {
        "path": "/site/services/4.jpg",
        "label": "4.jpg",
        "group": "Services",
        "usedOn": [
            "Service pages"
        ],
        "maxWidth": 1400
    },
    {
        "path": "/site/services/5.jpeg",
        "label": "5.jpeg",
        "group": "Services",
        "usedOn": [
            "Service pages"
        ],
        "maxWidth": 1400
    },
    {
        "path": "/site/services/6.jpg",
        "label": "6.jpg",
        "group": "Services",
        "usedOn": [
            "Service pages"
        ],
        "maxWidth": 1400
    },
    {
        "path": "/site/services/s1.jpg",
        "label": "s1.jpg",
        "group": "Services",
        "usedOn": [
            "Service pages"
        ],
        "maxWidth": 1400
    },
    {
        "path": "/site/services/s10.jpg",
        "label": "s10.jpg",
        "group": "Services",
        "usedOn": [
            "Service pages"
        ],
        "maxWidth": 1400
    },
    {
        "path": "/site/services/s11.jpg",
        "label": "s11.jpg",
        "group": "Services",
        "usedOn": [
            "Service pages"
        ],
        "maxWidth": 1400
    },
    {
        "path": "/site/services/s12.jpg",
        "label": "s12.jpg",
        "group": "Services",
        "usedOn": [
            "Service pages"
        ],
        "maxWidth": 1400
    },
    {
        "path": "/site/services/s14.jpg",
        "label": "s14.jpg",
        "group": "Services",
        "usedOn": [
            "Service pages"
        ],
        "maxWidth": 1400
    },
    {
        "path": "/site/services/s15.jpg",
        "label": "s15.jpg",
        "group": "Services",
        "usedOn": [
            "Service pages"
        ],
        "maxWidth": 1400
    },
    {
        "path": "/site/services/s2.jpg",
        "label": "s2.jpg",
        "group": "Services",
        "usedOn": [
            "Service pages"
        ],
        "maxWidth": 1400
    },
    {
        "path": "/site/services/s3.jpg",
        "label": "s3.jpg",
        "group": "Services",
        "usedOn": [
            "Service pages"
        ],
        "maxWidth": 1400
    },
    {
        "path": "/site/services/s4.jpg",
        "label": "s4.jpg",
        "group": "Services",
        "usedOn": [
            "Service pages"
        ],
        "maxWidth": 1400
    },
    {
        "path": "/site/services/s5.jpg",
        "label": "s5.jpg",
        "group": "Services",
        "usedOn": [
            "Service pages"
        ],
        "maxWidth": 1400
    },
    {
        "path": "/site/services/s6.jpg",
        "label": "s6.jpg",
        "group": "Services",
        "usedOn": [
            "Service pages"
        ],
        "maxWidth": 1400
    },
    {
        "path": "/site/services/s7.jpg",
        "label": "s7.jpg",
        "group": "Services",
        "usedOn": [
            "Service pages"
        ],
        "maxWidth": 1400
    },
    {
        "path": "/site/services/sms.png",
        "label": "sms.png",
        "group": "Services",
        "usedOn": [
            "Service pages"
        ],
        "maxWidth": 1400
    }
];
